# frozen_string_literal: true

source 'https://rubygems.org'

gem 'artii', '~> 2.1', '>= 2.1.2'
gem 'bundler', '~> 2.1', '>= 2.1.4'
gem 'colorize', '~> 0.8.1'
gem 'json', '~> 2.6', '>= 2.6.1'
gem 'logger', '~> 1.5', '>= 1.5.1'
gem 'rspec', '~> 3.11'
gem 'rubocop', '~> 1.27'
gem 'rubocop-shopify', '~> 2.5'
